# GitLab CI script for publishing on gitlab pages
image: registry.gitlab.com/kpmeen/docker-scala-sbt:scala_2.12

pages:
  script:
  - curl -L -o /usr/local/bin/amm https://git.io/vdNv2 && chmod +x /usr/local/bin/amm
  - cd _build
  - amm Publish.sc
  artifacts:
    paths:
    - index.html
    - assets
    - config
    - pages
    - posts
    - sitemap.xml
    - CNAME
    - 404.html
  only:
  - master
