image: registry.gitlab.com/kpmeen/docker-scala-sbt:scala_2.13_jdk11

variables:
  CI: "true"
  DOCKER_DRIVER: overlay
  # Setting specific folder for sbt-coursier to cache artifacts
  COURSIER_CACHE: "/root/cache/coursier"

cache:
  untracked: true
  paths:
    - cache

stages:
  - build
  - deploy

pages:scalac:
  stage: build
  tags:
    - docker
  script:
    - cd _project
    - sbt fullOptJS
    - cd ..
  artifacts:
    paths:
      - _project/target
      - assets

pages:build:
  stage: build
  tags:
    - docker
  dependencies:
    - pages:scalac
  script:
    - cd _build
    - curl -L https://github.com/lihaoyi/ammonite/releases/download/2.3.8/2.13-2.3.8-bootstrap > amm && chmod +x amm
    - ./amm Publish.sc
    - cd ..
    - rm -rf .build
    - mkdir .build
    - cp *.html .build
    - cp CNAME .build
    - cp sitemap.xml .build
    - cp -r assets .build
    - cp -r config .build
    - cp -r pages .build
    - cp -r posts .build
  artifacts:
    paths:
      - .build
  only:
    refs:
      - master

pages:
  stage: deploy
  dependencies:
    - pages:build
  script:
    - rm -rf public
    - mv .build public
  artifacts:
    paths:
      - public
  only:
    refs:
      - master
