# GitLab CI script for publishing on gitlab pages
image: registry.gitlab.com/kpmeen/docker-scala-sbt:scala_2.12

pages:
  script:
  - curl -L -o /usr/local/bin/amm https://git.io/vdNv2 && chmod +x /usr/local/bin/amm
  - cd _build
  - amm Publish.sc
  - cd ..
  - mkdir public
  - mv index.html public
  - mv assets public
  - mv config public
  - mv pages public
  - mv posts public
  - mv sitemap.xml public
  - mv CNAME public
  - mv 404.html public
  artifacts:
    paths:
    - public
  only:
  - master
